# scamp_default_instruments.py
# A list of the instrument names in the default scamp
# soundfont.

PITCHED_PERCUSSIVE_INSTRUMENT_NAMES = [
    "Glockenspiel",
    "Bright Piano",
    "Harp LP2",
    "Kalimba",
    "Xylophone",
    "Celesta",
    "Vibraphone",
    "Marimba",
    "Wood Block",
    "Pizzicato Strings",
    "Steel Guitar PH",
    "Guitar Nylon X",
    "Honky Tonk",
    "E.Piano 1",
    "Clavinet",
    "Music Box",
    "Tubular Bells",
    "Dulcimer",
    "Timpani Half",
    "Orchestra Hit",
    "Piano Merlin",
    "Bottle Chiff",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Tinker Bell",
    "Steel Drum",
    "Taiko Drum",
    "Melodic Tom",
    "Coupled Harpsichord",
]

SUSTAIN_INSTRUMENT_NAMES = [
    "Synth Str 2",
    "Strings SP1",
    "Flute Gold",
    "Pan Flute",
    "Slow Strings SP",
    "French Horns",
    "Alto SAX",
    "Baritone Sax",
    "Tenor Sax New",
    "Harmonica",
    "Viola LP",
    "Soprano Sax",
    "Synth Strings 1",
    "Church Organ 2",
    "Contrabass",
    "Cello LP",
    "Violin LP3",
    "Oboe",
    "Clarinet",
    "Bassoon (Rea)",
    "English Horn (Rea)",
    "Organ 1",
    "Organ 2",
    "Organ 3",
    "Reed Organ",
    "Accordion",
    "Bandoneon",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Vox",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Mute Trumpet",
    "Brass",
    "Synth Brass 1",
    "Synth Brass 2",
    "Piccolo",
    "Recorder",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Synth Calliope",
    "Chiffer Lead",
    "Charang",
    "Solo Vox",
    "Fantasia",
    "Warm Pad",
    "Poly Synth",
    "Space Voice",
    "Bowed Glass",
    "Metal Pad",
    "Halo Pad",
    "Sweep Pad",
    "Ice Rain",
    "Soundtrack",
    "Crystal",
    "Atmosphere",
    "Brightness",
    "Goblin",
    "Echo Drops",
    "Star Theme",
]

STANDARD_INSTRUMENT_NAMES = [
    "Timpani Half",
    "Synth Str 2",
    "Glockenspiel",
    "Strings SP1",
    "Flute Gold",
    "Pan Flute",
    "Bright Piano",
    "Piano Merlin",
    "Slow Strings SP",
    "French Horns",
    "Orchestra",
    "Jazz",
    "TR 808",
    "Power",
    "Standard",
    "Tremolande",
    "Harp LP2",
    "Pizzicato Strings",
    "Steel Guitar PH",
    "Alto SAX",
    "Baritone Sax",
    "Tenor Sax New",
    "Guitar Nylon X",
    "Harmonica",
    "Viola LP",
    "Soprano Sax",
    "Jazz Guitar",
    "Xylophone",
    "Marimba",
    "Synth Strings 1",
    "Church Organ 2",
    "Contrabass",
    "Cello LP",
    "Violin LP3",
    "Oboe",
    "Clarinet",
    "Bassoon (Rea)",
    "English Horn (Rea)",
    "Piano 3",
    "Honky Tonk",
    "E.Piano 1",
    "E.Piano 2",
    "Clavinet",
    "Celesta",
    "Music Box",
    "Vibraphone",
    "Tubular Bells",
    "Dulcimer",
    "Organ 1",
    "Organ 2",
    "Organ 3",
    "Reed Organ",
    "Accordion",
    "Bandoneon",
    "Clean Guitar",
    "Guitar Mutes",
    "Overdrive Guitar",
    "DistortionGuitar",
    "Guitar Harmonics",
    "Acoustic Bass",
    "Fingered Bass",
    "Picked Bass",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Vox",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Mute Trumpet",
    "Brass",
    "Synth Brass 1",
    "Synth Brass 2",
    "Piccolo",
    "Recorder",
    "Bottle Chiff",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Square Wave",
    "Saw Wave",
    "Synth Calliope",
    "Chiffer Lead",
    "Charang",
    "Solo Vox",
    "5th Saw Wave",
    "Bass & Lead",
    "Fantasia",
    "Warm Pad",
    "Poly Synth",
    "Space Voice",
    "Bowed Glass",
    "Metal Pad",
    "Halo Pad",
    "Sweep Pad",
    "Ice Rain",
    "Soundtrack",
    "Crystal",
    "Atmosphere",
    "Brightness",
    "Goblin",
    "Echo Drops",
    "Star Theme",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bagpipe",
    "Fiddle",
    "Shenai",
    "Tinker Bell",
    "Agogo",
    "Steel Drum",
    "Wood Block",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Fret Noise",
    "Breath Noise",
    "Seashore",
    "Bird",
    "Telephone",
    "Helicopter",
    "Applause",
    "Gun Shot",
    "Coupled Harpsichord",
]
